KateFordLedger/Models/BankAccount.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace KateFordLedger.Models
{
    public enum AccountType { Checking = 0, Savings = 1, Loan = 3 }

    public class BankAccount
    {
        [Key]
        public Guid BankAccountId { get; set; }

        [Display(Name = "Account Number")]
        [RegularExpression("^[1-9][0-9]*$", ErrorMessage = "Please enter an Account Number greater than zero")]
        public int BankAccountNumber { get; set; }

        [Display(Name = "Date Opened")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTimeOffset BankAccountDateCreated { get; set; }

        [Display(Name = "Account Type")]
        public AccountType BankAccountType { get; set; }

        [Display(Name = "Balance")]
        [DataType(DataType.Currency)]
        [Range(0, (double)decimal.MaxValue, ErrorMessage = "Value should be between {1} and {2}.")]
        public decimal BankAccountBalance { get; set; } 
       
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ApplicationUser User { get; set; }

        public BankAccount()
            {
            }

      }
}

KateFordLedger/Controllers/BankAccountController.cs
using System;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using KateFordLedger.Models;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Data;

namespace KateFordLedger.Controllers
{
    public class BankAccountController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BankAccount
        public async Task<ActionResult> Index()
        {
            if (User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Index","Home");
            }

            var userId = User.Identity.GetUserId();
            var bankAccounts = db.BankAccounts.Where(x => x.User.Id == userId);
            return View(await bankAccounts.ToListAsync());
        }

        // GET: BankAccount/Details/5
        public async Task<ActionResult> Details(Guid? bankAccountId)
        {
            if (bankAccountId == null)
            {
                return RedirectToAction("Index");
            }
            BankAccount bankAccount = await db.BankAccounts.FindAsync(bankAccountId);
            if (bankAccount == null)
            {
                return HttpNotFound();
            }
            return View(bankAccount);
        }

        // GET: BankAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BankAccount/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "bankAccountNumber,bankAccountDateCreated,bankAccountType,bankAccountBalance")] BankAccount bankAccount)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Index");
            try
            {
                if (ModelState.IsValid)
                {
                    var userId = User.Identity.GetUserId();
                    bankAccount.User = db.Users.Single(u => u.Id == userId);
                    bankAccount.BankAccountId = Guid.NewGuid();
                    bankAccount.BankAccountDateCreated = DateTime.Today;
                    db.BankAccounts.Add(bankAccount);
                    await db.SaveChangesAsync();
                }
            }
            catch (DataException)
            {
                // error handling structure only
                ModelState.AddModelError("", "Unable to save changes.");
             }
            return RedirectToAction("Index");
        }

        // GET: BankAccount/Edit/5
        public async Task<ActionResult> Edit(Guid? bankAccountId)
        {
            if (bankAccountId == null)
            {
                return RedirectToAction("Index");
            }

            BankAccount bankAccount = await db.BankAccounts.FindAsync(bankAccountId);

            if (bankAccount == null)
            {
                return HttpNotFound();
            }
          return View(bankAccount);
        }

        // POST: BankAccount/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "BankAccountId,BankAccountNumber,BankAccountDateCreated,BankAccountType,BankAccountBalance")] BankAccount bankAccount)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Index");
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(bankAccount).State = EntityState.Modified;
                   await db.SaveChangesAsync();
                }
            }
            catch (DataException)
            {
                // error handling structure only
                ModelState.AddModelError("", "Unable to save changes");
             }
            return RedirectToAction("Index");
        }

        // GET: BankAccount/Delete/5
        public async Task<ActionResult> Delete(Guid? bankAccountId)
        {
            if (bankAccountId == null)
            {
                return RedirectToAction("Index");
            }

            BankAccount bankAccount = await db.BankAccounts.FindAsync(bankAccountId);

            if (bankAccount == null)
            {
                return HttpNotFound();
            }
          return View(bankAccount);
        }

        // POST: BankAccount/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid bankAccountId)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Index");
            try
            {
                if (ModelState.IsValid)
                {
                   BankAccount bankAccount = await db.BankAccounts.FindAsync(bankAccountId);
                   db.BankAccounts.Remove(bankAccount);
                   await db.SaveChangesAsync();
                }
            }
            catch (DataException)
            {
                // error handling structure only
                ModelState.AddModelError("", "Unable to save changes");
            }
          return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KateFordLedger/Views/BankAccount/Create.cshtml
@model KateFordLedger.Models.BankAccount

@{
    ViewBag.Title = "Create";
}

<h2>Create Account</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
         <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BankAccountNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BankAccountNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BankAccountNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BankAccountType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.BankAccountType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BankAccountType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BankAccountBalance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BankAccountBalance, new { htmlAttributes = new { @class = "form-control", @Value = 0 } })
                @Html.ValidationMessageFor(model => model.BankAccountBalance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index","BankAccount")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KateFordLedger/Views/BankAccount/Delete.cshtml
@model KateFordLedger.Models.BankAccount

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Account</h2>
<h4>Are you sure you want to delete this and all associated transactions?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BankAccountNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAccountNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankAccountDateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAccountDateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankAccountType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAccountType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankAccountBalance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAccountBalance)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
             @Html.ActionLink("Back to List", "Index", "BankAccount") | 
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

KateFordLedger/Views/BankAccount/Details.cshtml
@model KateFordLedger.Models.BankAccount

@{
    ViewBag.Title = "Details";
}

<h2>Account Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BankAccountNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAccountNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankAccountDateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAccountDateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankAccountType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAccountType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankAccountBalance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAccountBalance)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { bankAccountId = Model.BankAccountId }) |
    @Html.ActionLink("Back to List", "Index", "BankAccount")
</p>

KateFordLedger/Views/BankAccount/Edit.cshtml
@model KateFordLedger.Models.BankAccount

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Account</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BankAccountId)

        <div class="form-group">
            @Html.LabelFor(model => model.BankAccountNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BankAccountNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BankAccountNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BankAccountType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.BankAccountType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BankAccountType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BankAccountBalance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BankAccountBalance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BankAccountBalance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "BankAccount")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KateFordLedger/Views/BankAccount/Index.cshtml
@model IEnumerable<KateFordLedger.Models.BankAccount>

@{
    ViewBag.Title = "Accounts";
}

<h2>Accounts</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BankAccountNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BankAccountType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BankAccountDateCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BankAccountBalance)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BankAccountNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BankAccountType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BankAccountDateCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BankAccountBalance)
        </td>
        <td>
            @Html.ActionLink("Transactions", "Index", "Transaction", new { bankAccountId = item.BankAccountId }, new { @class = "btn btn-default" })
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { bankAccountId=item.BankAccountId }) |
            @Html.ActionLink("Details", "Details", new { bankAccountId = item.BankAccountId }) |
            @Html.ActionLink("Delete", "Delete", new { bankAccountId = item.BankAccountId })
        </td>
    </tr>
}

</table>